const races = [
  {
    name: "Human",
    img: "",
    imgSrc: "delapouite/person.svg",
    color: "beige",
    consumption: [{ wheat: 1 }],
    production: [{ money: 1 }],
  },
  {
    name: "Dwarf",
    img: "",
    imgSrc: "kier-heyl/dwarf-helmet.svg",
    color: "gold",
    metalworkingBonus: 1,
    farmingBonus: -0.5,
    consumption: [{ wheat: 1 }],
    production: [{ money: 1 }],
  },
  {
    name: "Elf",
    img: "",
    imgSrc: "kier-heyl/elf-helmet.svg",
    color: "green",
    metalworkingBonus: -0.5,
    farmingBonus: 1,
    consumption: [{ wheat: 1 }],
    production: [{ money: 1 }],
  },
];
const resources = [
  {
    id: "wheat",
    name: "Wheat",
    img: "",
    imgSrc: "lorc/wheat.svg",
    color: "wheat",
  },
  {
    id: "ore_iron",
    name: "Iron Ore",
    img: "",
    imgSrc: "faithtoken/ore.svg",
    color: "rgb(204, 148, 130)",
  },
  {
    id: "ore_copper",
    name: "Copper Ore",
    img: "",
    imgSrc: "faithtoken/ore.svg",
    color: "rgb(31, 128, 129)",
  },
  {
    id: "ore_tin",
    name: "Tin Ore",
    img: "",
    imgSrc: "faithtoken/ore.svg",
    color: "rgb(179, 179, 179)",
  },
  {
    id: "money",
    name: "Gold Coins",
    img: "",
    imgSrc: "lorc/crown-coin.svg",
    color: "gold",
  },
  {
    id: "iron_ingot",
    name: "Iron Ingot",
    img: "",
    imgSrc: "lorc/metal-bar.svg",
    color: "rgba(165, 163, 163, 1)",
  },
];
